"""
Email Alerts Module
=====================
Sends email alerts when BUY or SELL signals are detected.
Uses Gmail SMTP — free, no extra services needed.

Setup:
    1. Add to your .env file (or Streamlit secrets):
        ALERT_EMAIL=your.email@gmail.com
        ALERT_EMAIL_PASSWORD=your-app-password
        ALERT_TO_EMAIL=where-to-send@email.com

    2. Gmail requires an App Password (not your regular password):
        - Go to myaccount.google.com
        - Security → 2-Step Verification → App Passwords
        - Create a new app password for "Mail"
        - Use that 16-character password here

DISCLAIMER: For educational/portfolio purposes only. Not financial advice.
"""

import os
import smtplib
import logging
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime
from dotenv import load_dotenv

load_dotenv()
logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
logger = logging.getLogger(__name__)

ALERT_EMAIL          = os.getenv("ALERT_EMAIL")
ALERT_EMAIL_PASSWORD = os.getenv("ALERT_EMAIL_PASSWORD")
ALERT_TO_EMAIL       = os.getenv("ALERT_TO_EMAIL", ALERT_EMAIL)


# ─────────────────────────────────────────────
# 1. Email Builder
# ─────────────────────────────────────────────

def build_email_html(triggered: list[dict], analysis: dict) -> str:
    """Builds a clean HTML email body from triggered alerts."""

    def signal_color(rec):
        return {"BUY": "#22c55e", "SELL": "#ef4444"}.get(rec, "#f59e0b")

    def signal_icon(rec):
        return {"BUY": "▲", "SELL": "▼"}.get(rec, "●")

    rows = ""
    for item in triggered:
        rec    = item["recommendation"]
        color  = signal_color(rec)
        icon   = signal_icon(rec)
        rows += f"""
        <tr>
            <td style="padding:12px;border-bottom:1px solid #eee;font-weight:bold">{item['ticker']}</td>
            <td style="padding:12px;border-bottom:1px solid #eee;color:{color};font-weight:bold">{icon} {rec}</td>
            <td style="padding:12px;border-bottom:1px solid #eee">{item['confidence']}/10</td>
            <td style="padding:12px;border-bottom:1px solid #eee;color:#666;font-size:13px">{item['reasoning']}</td>
        </tr>"""

    macro = analysis.get("macro_environment", "")
    summary = analysis.get("market_summary", "")
    date = analysis.get("analysis_date", datetime.utcnow().strftime("%Y-%m-%d"))

    return f"""
    <html><body style="font-family:Arial,sans-serif;max-width:700px;margin:0 auto;padding:20px">
        <div style="background:#1F4E79;color:white;padding:20px;border-radius:8px 8px 0 0">
            <h2 style="margin:0">Stock Analysis Alert</h2>
            <p style="margin:4px 0 0;opacity:0.8">{date}</p>
        </div>
        <div style="background:#fff3cd;border:1px solid #ffc107;padding:12px;font-size:13px;color:#856404">
            ⚠️ For educational purposes only. Not financial advice.
        </div>
        <div style="padding:20px;background:#f8f9fa;border:1px solid #eee">
            <h3 style="margin:0 0 8px;color:#1F4E79">Triggered Signals</h3>
            <table style="width:100%;border-collapse:collapse;background:white;border-radius:8px;overflow:hidden;box-shadow:0 1px 3px rgba(0,0,0,0.1)">
                <thead>
                    <tr style="background:#1F4E79;color:white">
                        <th style="padding:12px;text-align:left">Ticker</th>
                        <th style="padding:12px;text-align:left">Signal</th>
                        <th style="padding:12px;text-align:left">Confidence</th>
                        <th style="padding:12px;text-align:left">Reasoning</th>
                    </tr>
                </thead>
                <tbody>{rows}</tbody>
            </table>
        </div>
        {"<div style='padding:16px 20px;background:#e8f4f8;border:1px solid #bee5eb'><strong>Macro:</strong> " + macro + "</div>" if macro else ""}
        {"<div style='padding:16px 20px;background:#fff;border:1px solid #eee'><strong>Market overview:</strong> " + summary + "</div>" if summary else ""}
        <div style="padding:12px 20px;background:#f8f9fa;border:1px solid #eee;font-size:12px;color:#999;text-align:center">
            Generated by AI Stock Analysis Bot · Educational use only · Not financial advice
        </div>
    </body></html>"""


def build_email_text(triggered: list[dict], analysis: dict) -> str:
    """Plain text fallback for email clients that don't support HTML."""
    lines = [
        "STOCK ANALYSIS ALERT",
        f"Date: {analysis.get('analysis_date', datetime.utcnow().strftime('%Y-%m-%d'))}",
        "=" * 50,
        "DISCLAIMER: For educational purposes only. Not financial advice.",
        "",
        "TRIGGERED SIGNALS:",
    ]
    for item in triggered:
        lines += [
            f"  {item['ticker']}: {item['recommendation']} (Confidence: {item['confidence']}/10)",
            f"  Reasoning: {item['reasoning']}",
            "",
        ]
    if macro := analysis.get("macro_environment"):
        lines += ["MACRO CONTEXT:", macro, ""]
    if summary := analysis.get("market_summary"):
        lines += ["MARKET OVERVIEW:", summary]
    return "\n".join(lines)


# ─────────────────────────────────────────────
# 2. Send Email
# ─────────────────────────────────────────────

def send_alert_email(triggered: list[dict], analysis: dict) -> bool:
    """
    Sends an alert email for triggered BUY/SELL signals.

    Args:
        triggered: list of recommendation dicts that triggered alerts
        analysis:  full analysis dict for context

    Returns:
        True if sent successfully, False otherwise.
    """
    if not ALERT_EMAIL or not ALERT_EMAIL_PASSWORD:
        logger.warning("Email alerts not configured — add ALERT_EMAIL and ALERT_EMAIL_PASSWORD to .env")
        return False

    if not triggered:
        logger.info("No signals triggered — no email sent.")
        return False

    tickers  = ", ".join(t["ticker"] for t in triggered)
    signals  = ", ".join(f"{t['ticker']} {t['recommendation']}" for t in triggered)
    subject  = f"Stock Alert: {signals} — {datetime.utcnow().strftime('%Y-%m-%d')}"

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"]    = ALERT_EMAIL
    msg["To"]      = ALERT_TO_EMAIL

    msg.attach(MIMEText(build_email_text(triggered, analysis), "plain"))
    msg.attach(MIMEText(build_email_html(triggered, analysis), "html"))

    try:
        with smtplib.SMTP("smtp.mail.me.com", 587) as server:
            server.starttls()
            server.login(ALERT_EMAIL, ALERT_EMAIL_PASSWORD)
            server.sendmail(ALERT_EMAIL, ALERT_TO_EMAIL, msg.as_string())
        logger.info(f"Alert email sent for: {tickers}")
        return True
    except smtplib.SMTPAuthenticationError:
        logger.error("Email authentication failed — check your credentials")
        return False
    except Exception as e:
        logger.error(f"Failed to send alert email: {e}")
        return False


# ─────────────────────────────────────────────
# 3. Check & Send Alerts
# ─────────────────────────────────────────────

def check_and_send_alerts(
    analysis: dict,
    alert_on: list[str] = ["BUY", "SELL"],
    min_confidence: int = 6,
) -> list[dict]:
    """
    Checks analysis results for triggered signals and sends email if found.

    Args:
        analysis:       full analysis dict from analyze_stocks()
        alert_on:       which signals to alert on — ["BUY", "SELL"] or ["BUY"] only
        min_confidence: minimum confidence score to trigger an alert (1-10)

    Returns:
        List of recommendations that triggered alerts.
    """
    if "error" in analysis:
        logger.warning("Analysis contains errors — skipping alerts")
        return []

    triggered = [
        rec for rec in analysis.get("recommendations", [])
        if rec.get("recommendation") in alert_on
        and rec.get("confidence", 0) >= min_confidence
    ]

    if triggered:
        logger.info(f"Alert triggered for: {[t['ticker'] for t in triggered]}")
        sent = send_alert_email(triggered, analysis)
        if sent:
            logger.info("Alert email sent successfully.")
        else:
            logger.warning("Alert email not sent — check email configuration.")
    else:
        logger.info("No alerts triggered for this analysis.")

    return triggered


# ─────────────────────────────────────────────
# 4. Demo
# ─────────────────────────────────────────────

if __name__ == "__main__":
    print("=" * 60)
    print("Email Alerts Module — Config Check")
    print("=" * 60)

    if ALERT_EMAIL and ALERT_EMAIL_PASSWORD:
        print(f"✓ From email  : {ALERT_EMAIL}")
        print(f"✓ To email    : {ALERT_TO_EMAIL}")
        print("✓ Password    : configured")
        print("\nEmail alerts are ready to go!")
    else:
        print("✗ Not configured. Add to your .env file:")
        print("  ALERT_EMAIL=your.gmail@gmail.com")
        print("  ALERT_EMAIL_PASSWORD=your-16-char-app-password")
        print("  ALERT_TO_EMAIL=destination@email.com")
        print("\nGet a Gmail App Password at:")
        print("  myaccount.google.com → Security → App Passwords")
